import {
  IconAWS, IconAveva, IconIntel, IconGlobe, IconStar, IconMic,
  IconLayers, IconChip, IconBolt, IconTrophy,
} from "@/components/icons";

export const experiences = [
  {
    role: "Software Development Engineer Intern",
    company: "Amazon Web Services",
    team: "AWS Elemental · MediaPackage",
    period: "May – Aug 2026",
    location: "Portland, OR",
    icon: <IconAWS className="w-5 h-5" />,
    iconBg: "bg-orange-100 text-orange-600",
    bullets: [
      "Engineered SCTE-35-based clip harvesting for MediaPackage in Kotlin & C++, letting customers harvest segments via ad-marker cues instead of manual timestamps, across both HLS and DASH adaptive streaming.",
      "Shipped 2 CRs overhauling the alarm system, surfacing ~40% more previously-missed Sev-2 and Sev-3 incidents.",
      "Served in the team's on-call rotation, triaging and responding to production incidents.",
      "Won the org-wide AWS hackathon, earning the Impact Award for greatest potential customer & business value.",
    ],
    tags: ["Kotlin", "C++", "SCTE-35", "MediaPackage", "HLS / DASH"],
    stat: { n: "~40%", l: "more Sev-2/3 caught" },
  },
  {
    role: "Software Engineering Intern",
    company: "AVEVA",
    team: "ChangeBroker Platform",
    period: "May – Aug 2025",
    location: "Scottsdale, AZ",
    icon: <IconAveva className="w-5 h-5" />,
    iconBg: "bg-violet-100 text-violet-600",
    bullets: [
      "Architected C# .NET microservices processing 150M+ daily IoT data streams across 1,000+ global manufacturing facilities.",
      "Engineered RESTful & Minimal APIs serving 50,000+ concurrent requests daily with multi-layer architecture.",
      "Achieved 95% CI/CD code coverage; managed production Kubernetes deployments with Helm charts.",
    ],
    tags: ["C# / .NET", "Microservices", "Kubernetes", "REST APIs"],
    stat: { n: "150M+", l: "streams / day" },
  },
  {
    role: "Software Engineering Intern",
    company: "Intel Corporation",
    team: "Data Center AI Group",
    period: "May – Aug 2024",
    location: "Hillsboro, OR",
    icon: <IconIntel className="w-5 h-5" />,
    iconBg: "bg-blue-100 text-blue-600",
    bullets: [
      "Automated Cadence EDA privilege management for 1,000+ engineers, cutting provisioning from 3+ days to under 2 hours.",
      "Optimized PCB export scripts: 99.95% runtime reduction (40+ hrs → 2 min), ~70% fewer export failures.",
    ],
    tags: ["Python", "Perl", "Automation", "EDA Tools"],
    stat: { n: "99.95%", l: "runtime reduction" },
  },
];

export const projects = [
  {
    title: "Sahil's Portfolio",
    award: "Personal Website · 2026",
    desc: "A navigable World Labs Marble 3D Gaussian-splat hero rendered with Spark, scroll-driven first-person camera, and a liquid-glass design system, built with Next.js and TypeScript.",
    stats: [{ v: "WebGL", l: "Splat hero" }, { v: "Next.js", l: "Framework" }, { v: "Framer", l: "Animations" }],
    tags: ["Next.js", "TypeScript", "Three.js", "World Labs"],
    icon: <IconGlobe className="w-6 h-6" />,
    iconBg: "bg-indigo-100 text-indigo-600",
    href: "https://github.com/sapai5/SahilWebsite",
  },
  {
    title: "Equalify",
    award: "1st Place · Fidelity Fintech · Sunhacks",
    desc: "Scholarship discovery platform aggregating $1M+ in opportunities for underrepresented students with intelligent demographic matching.",
    stats: [{ v: "$1M+", l: "Opportunities" }, { v: "85%", l: "Faster" }, { v: "200+", l: "Users" }],
    tags: ["Next.js", "Web Scraping", "ML Matching"],
    icon: <IconStar className="w-6 h-6" />,
    iconBg: "bg-emerald-100 text-emerald-600",
    href: "https://github.com/sapai5/equalify",
  },
  {
    title: "Multiview Ad Insertion",
    award: "AWS Hackathon · Impact Award",
    desc: "Dynamic ad insertion for AWS Elemental MediaLive multiview, splicing targeted ads into multi-program mosaic streams. Won the org-wide AWS hackathon's Impact Award for customer and business value.",
    stats: [{ v: "Impact", l: "Award" }, { v: "Multiview", l: "MediaLive" }, { v: "Live", l: "Ad Insertion" }],
    tags: ["AWS", "MediaLive", "SCTE-35", "Live Video"],
    icon: <IconAWS className="w-6 h-6" />,
    iconBg: "bg-orange-100 text-orange-600",
    href: "https://aws.amazon.com/medialive/",
  },
  {
    title: "Chess.com AI Overlay",
    award: "Personal Project · 2026",
    desc: "A vision-based chess assistant that reads the board straight from your screen, classifies pieces with a custom PyTorch ResNet-18 CNN, builds the FEN, and queries Stockfish for the best move, all in a transparent Electron overlay with a Gemini coach.",
    stats: [{ v: "ResNet-18", l: "CNN" }, { v: "Stockfish", l: "Engine" }, { v: "Electron", l: "Overlay" }],
    tags: ["Python", "PyTorch", "Computer Vision", "Electron"],
    icon: <IconChip className="w-6 h-6" />,
    iconBg: "bg-cyan-100 text-cyan-600",
    href: "https://github.com/sapai5/chessAI",
  },
  {
    title: "ReasoningGPA",
    award: "CSE 476 · Arizona State University",
    desc: "A general-purpose inference-time reasoning agent that boosts LLM accuracy with 10 techniques (domain-aware routing, chain-of-thought, self-consistency, step-back, debate, self-refine) selected per question type.",
    stats: [{ v: "10", l: "Techniques" }, { v: "Agentic", l: "Reasoning" }, { v: "Qwen3", l: "LLM" }],
    tags: ["Python", "LLMs", "Prompting", "Agents"],
    icon: <IconBolt className="w-6 h-6" />,
    iconBg: "bg-fuchsia-100 text-fuchsia-600",
    href: "https://github.com/sapai5/ReasoningGPA",
  },
  {
    title: "GlobeTrail",
    award: "Sunhacks · Arizona State University",
    desc: "Agentic travel planning using Model Context Protocol to autonomously book flights, hotels, and activities with an interactive 3D globe.",
    stats: [{ v: "MCP", l: "Architecture" }, { v: "3D", l: "Globe viz" }, { v: "Live", l: "Pricing" }],
    tags: ["Three.js", "React", "MCP", "Agentic AI"],
    icon: <IconGlobe className="w-6 h-6" />,
    iconBg: "bg-sky-100 text-sky-600",
    href: "https://github.com/sapai5/globetrail",
  },
  {
    title: "Interview Lens",
    award: "Hackathon · SoDA 2024",
    desc: "Real-time interview coaching dashboard using computer vision & speech-to-text. Tracks eye contact, filler words, speech pace, and facial expressions via AWS Rekognition and Transcribe.",
    stats: [{ v: "Real-time", l: "CV Analysis" }, { v: "AWS", l: "Rekognition" }, { v: "4", l: "Contributors" }],
    tags: ["Python", "Streamlit", "AWS", "Computer Vision"],
    icon: <IconMic className="w-6 h-6" />,
    iconBg: "bg-rose-100 text-rose-600",
    href: "https://github.com/sapai5/Interview-Lens",
  },
  {
    title: "NoteFlow",
    award: "CSE412 · Arizona State University",
    desc: "Full-stack collaborative note-taking app with real-time sync, rich text editing, and course-organized notebooks for university students.",
    stats: [{ v: "Real-time", l: "Sync" }, { v: "Full-Stack", l: "App" }, { v: "DB", l: "Backed" }],
    tags: ["React", "Node.js", "PostgreSQL", "Full-Stack"],
    icon: <IconLayers className="w-6 h-6" />,
    iconBg: "bg-amber-100 text-amber-600",
    href: "https://github.com/sapai5/CSE412-Noteflow",
  },
  {
    title: "Mining AI",
    award: "AVEVA EcoTech · Global #1 Winner",
    desc: "CNN + decision-tree model predicting toxic mineral deposit locations with 95% accuracy to help mining companies reduce environmental impact.",
    stats: [{ v: "95%", l: "Accuracy" }, { v: "CNN", l: "Architecture" }, { v: "Global #1", l: "Winner" }],
    tags: ["Python", "TensorFlow", "CNNs", "Gemini API"],
    icon: <IconChip className="w-6 h-6" />,
    iconBg: "bg-violet-100 text-violet-600",
    href: "https://github.com/sapai5/miningAI",
  },
  {
    title: "NeetCode GitHub Sync",
    award: "Chrome Extension · Open Source",
    desc: "Chrome extension that automatically pushes LeetCode solutions from NeetCode.io to a personal GitHub repository after every submission.",
    stats: [{ v: "Auto", l: "GitHub Push" }, { v: "Chrome", l: "Extension" }, { v: "Open", l: "Source" }],
    tags: ["JavaScript", "Chrome APIs", "GitHub API"],
    icon: <IconBolt className="w-6 h-6" />,
    iconBg: "bg-blue-100 text-blue-600",
    href: "https://github.com/sapai5/neetcode-github-sync-chrome-extension",
  },
  {
    title: "StudyMatch",
    award: "Software Developer's Club Hackathon · ASU",
    desc: "Competitive hackathon submission building a platform to connect students for study sessions similar to Tinder.",
    stats: [{ v: "K-Means", l: "Clustering" }, { v: "Tinder", l: "UI/UX" }, { v: "Webscraped", l: "Data" }],
    tags: ["Python", "LLMs", "GitHub API", "DevOps"],
    icon: <IconTrophy className="w-6 h-6" />,
    iconBg: "bg-teal-100 text-teal-600",
    href: "https://github.com/sapai5/SoDA2024Hack",
  },
];

export const skills = [
  { cat: "Languages", items: ["C#", "C++", "Java", "Python", "Kotlin", "Go", "SQL", "LINQ", "JavaScript", "TypeScript", "Perl"] },
  { cat: "Frameworks", items: ["ASP.NET Core", ".NET Framework", "React", "Next.js", "Node.js", "Three.js", "Express", "TensorFlow"] },
  { cat: "Cloud & DevOps", items: ["AWS (EC2, S3, Lambda)", "Azure", "Docker", "Kubernetes", "Helm", "CI/CD", "Git", "Jenkins"] },
  { cat: "Tools & Data", items: ["MongoDB", "PostgreSQL", "Redis", "Postman", "Swagger", "RESTful APIs", "Microservices"] },
];

export const awards = [
  { n: "$19K", l: "Hackathon Winnings", sub: "4× Winner · 2024–2026", icon: <IconTrophy className="w-5 h-5" />, iconBg: "bg-amber-100 text-amber-600" },
  { n: "#1", l: "AVEVA AI Championship", sub: "100+ international teams", icon: <IconGlobe className="w-5 h-5" />, iconBg: "bg-violet-100 text-violet-600" },
  { n: "$4K", l: "Andy Grove Scholarship", sub: "Intel · STEM Excellence 2024", icon: <IconBolt className="w-5 h-5" />, iconBg: "bg-blue-100 text-blue-600" },
  { n: "6K+", l: "Executives Addressed", sub: "AVEVA World Conf · SF", icon: <IconMic className="w-5 h-5" />, iconBg: "bg-rose-100 text-rose-600" },
];
